import type { Project } from "./schema";

export type { Project, ProjectKind } from "./schema";

// Every project on the desktop. Written from each repository's README and from
// Uzair's CV; numbers that change as the code does (test counts) are true as
// of the day in `asOf`, and the assistant says so.

const GH = "https://github.com/f20230125-sudo";

export const projects: Project[] = [
  {
    id: "agent-desk",
    name: "Agent Desk",
    aliases: ["patch", "pitch", "github bot", "the github bot", "agent desk", "linkedin agent", "github agent"],
    kind: "flagship",
    tagline: "Two AI agents on one site: Patch looks after a GitHub account, Pitch drafts LinkedIn posts.",
    pitch:
      "Patch audits every GitHub repository, scores each one out of 100 and drafts fixes. Pitch turns Patch's notes into LinkedIn post drafts. Nothing is sent anywhere without a click, and the agents run on Uzair's own Claude plan with no API key.",
    facts: [
      "Patch scores every repository out of 100. The first audit of 12 repositories took 30 GitHub requests and 0 model calls.",
      "Rules come before the model: skip what has not changed, then rules, then at most one Claude call. A check that finds nothing changed costs one request.",
      "Claude runs through the Claude Code program (no API key anywhere) and Patch stops calling it at 40% of plan usage.",
      "Nothing reaches GitHub without a click. The list of possible writes is fixed in code and has no delete, no force-push and no push to a default branch; dry-run is on at the start.",
      "Pitch only drafts. Uzair presses Post himself on LinkedIn, and Pitch never touches LinkedIn.",
      "469 pytest tests on the backend, as of 7 October 2026.",
    ],
    decisions: [
      "Efficiency ladder: skip unchanged work, then rules, then one model call. Audits and syncs use no model at all, and tests measure the request and model counts so they cannot quietly get worse.",
      "The agent's writes are an allow-list in code. Text from the model cannot add to it.",
      "The hosted half, called GitHub Bot, is a GitHub Actions job that runs Patch every six hours with rules only. It commits a snapshot for a view-only site, and each suggestion opens GitHub's editor pre-filled, so no code-write token is held.",
      "Both agents' faces follow the portfolio score: 80 or more happy, 60 to 79 normal, under 60 sad.",
    ],
    limits: [
      "The working desk runs on Uzair's own PC, because Claude is only reachable through his signed-in Claude Code. The public site is a view-only copy.",
      "A public copy must not use his subscription for other people, so it never calls Claude.",
    ],
    stack: ["Next.js", "FastAPI", "SQLite", "Claude Code", "GitHub Actions", "Python", "TypeScript"],
    tags: ["agent", "agents", "automation", "github", "linkedin", "audit", "claude", "llm", "pytest", "fastapi", "vercel", "dry-run", "safety"],
    code: `${GH}/github-bot`,
    live: {
      url: "https://github-bot-wine.vercel.app",
      frameable: true,
      note: "This is the view-only copy. The working desk runs on Uzair's own PC.",
    },
    shots: [
      { src: "/media/agent-desk/floor.webp", alt: "The Floor of Agent Desk after an audit of 12 repositories, with a chat answer and eight proposals waiting for approval." },
      { src: "/media/agent-desk/patch.webp", alt: "Patch's page in Agent Desk, showing the portfolio score and findings per repository." },
      { src: "/media/agent-desk/proposal.webp", alt: "A proposal from Patch, with the change it wants to make and the buttons to approve or reject it." },
    ],
    icon: { glyph: "Bot", from: "#0f766e", to: "#14b8a6" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme", "cv"],
  },
  {
    id: "flowboard",
    name: "Flowboard",
    aliases: ["workflow builder", "the workflow one", "n8n", "n8n clone"],
    kind: "flagship",
    tagline: "A visual workflow builder, a small n8n: connect blocks, press Run, watch each step's real data.",
    pitch:
      "Drag eight kinds of block onto a canvas, connect them and press Run. A React-free engine runs the blocks that are ready in parallel and shows what each step received and returned. It calls real APIs from the browser and costs nothing to run.",
    facts: [
      "Eight block types: manual trigger, HTTP request, condition, set fields, filter list, AI step, delay and output.",
      "Flows cannot run code: there is no eval, and a reference to another step's data is a path lookup.",
      "The REST relay is hardened against SSRF: a host allow-list, no private addresses, no redirects, and caps on size and rate.",
      "319 unit tests and 37 end-to-end Playwright tests with axe accessibility scans, as of 7 October 2026.",
      "CI builds the Docker image, starts a container and applies the Kubernetes manifest to a real kind cluster.",
      "The AI step uses the visitor's own key for Gemini, Groq, OpenAI or a compatible service, and returns a labelled sample without one.",
    ],
    decisions: [
      "The engine is plain TypeScript with no React in it. It emits an event when a step starts, finishes or fails, and the store draws from those events.",
      "Undo and redo are hand-written, so a drag is one step and typing is merged.",
      "Flows are saved in the visitor's browser, so there is no database and no cost.",
      "A failed step stops the run and shows what the server said. An HTTP block can be given extra tries for a busy API.",
    ],
    limits: [
      "No loops and no arithmetic; Filter list covers the common for-each case.",
      "Editing needs a screen at least 1024 pixels wide. On a phone a flow can be opened and run, not edited.",
      "The Docker image and manifest run in CI on a test cluster, not on a production one.",
    ],
    stack: ["TypeScript", "Next.js", "React", "Redux Toolkit", "React Flow", "Zod", "Docker", "Kubernetes", "Playwright", "Vitest"],
    tags: ["n8n", "workflow", "automation", "canvas", "engine", "rest", "api", "ssrf", "security", "docker", "kubernetes", "k8s", "undo", "redux", "zod", "react flow"],
    code: `${GH}/flowboard`,
    live: {
      url: "https://flowboard-flax-seven.vercel.app",
      frameable: true,
      note: "Saved flows inside this window are kept apart from the ones you save on Flowboard's own site.",
    },
    gif: { src: "/media/flowboard/demo.gif", alt: "Flowboard in use: Run is pressed and each block lights up as it executes." },
    shots: [
      { src: "/media/flowboard/run.webp", alt: "A flow after a run: the path that was taken is lit, the other is faded, and the panel shows the result." },
      { src: "/media/flowboard/failed.webp", alt: "The run panel after a failed request, showing the error and what the server sent back." },
    ],
    icon: { glyph: "Workflow", from: "#7c3aed", to: "#a78bfa" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme", "cv"],
  },
  {
    id: "sayso",
    name: "Sayso",
    aliases: ["the airline one", "airline", "juno air", "service desk", "airline project"],
    kind: "flagship",
    tagline: "Say what you need, and the screen builds itself: a service desk for a made-up airline.",
    pitch:
      "A typed or spoken request is answered with working interface, such as a seat map, a price and a receipt, instead of text. A four-step agent (understand, plan, run, check) written in plain TypeScript chooses from 14 Zod-validated components.",
    facts: [
      "Eight journeys: trips, flight status, change a flight, choose a seat, add bags, check in, cancel and refund, book a flight. One sentence can ask for several and ends in one payment.",
      "The plan chooses, the code computes: the server re-prices every order and refuses a total that does not match.",
      "Rules read requests with no key. Measured on sentences written before tuning, 36 of 50 read correctly, then 24 of 30, then 20 of 25: 76% of 105 on first reading.",
      "A model is optional, through the visitor's own free key, called from the browser. The model may choose a layout but never a number.",
      "Voice input uses the browser's own speech recognition.",
      "369 unit tests and 59 end-to-end tests, with axe scans in both themes, as of 7 October 2026.",
    ],
    decisions: [
      "One schema, four uses: each component's Zod schema checks a plan, describes the component to a model, documents it on the gallery page and types the React component.",
      "A run is data, not a process. Waiting at step 4 for a seat is a value in the Redux store, so a reload keeps the seat map waiting.",
      "A change of mind re-plans instead of restarting, and keeps everything before the first step that differs.",
      "A request with a not in it is never taken as an order: the desk asks what to do instead of guessing.",
    ],
    limits: [
      "Juno Air is made up. Nothing is booked, charged or refunded.",
      "The rules read English and the common ways of asking. Expect about one fresh sentence in five to need a model or to get a polite do-not-understand.",
      "The model path is tested against a stand-in provider, and voice input only with a stand-in for the browser's recognition.",
    ],
    stack: ["TypeScript", "Next.js", "React", "Redux Toolkit", "Zod", "Tailwind CSS", "Playwright"],
    tags: ["agent", "agentic", "front-end", "frontend", "interface", "generative ui", "airline", "seat map", "voice", "speech", "components", "state machine", "redux", "tailwind", "nlu", "intent"],
    code: `${GH}/sayso`,
    live: {
      url: "https://sayso-sigma.vercel.app",
      frameable: true,
      microphone: true,
      note: "Bookings made in this window are kept apart from the ones on Sayso's own site.",
    },
    gif: { src: "/media/sayso/demo.gif", alt: "One sentence with three requests becomes a day picker, a flight list, a seat map and one price." },
    shots: [
      { src: "/media/sayso/desk.webp", alt: "Sayso partway through a request, with the How it worked panel open beside it." },
      { src: "/media/sayso/receipt-dark.webp", alt: "A receipt in Sayso's dark theme, with the checks listed underneath." },
    ],
    icon: { glyph: "PlaneTakeoff", from: "#2563eb", to: "#60a5fa" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme", "cv"],
  },
  {
    id: "hindsight",
    name: "Hindsight",
    aliases: ["observer", "the observer", "timeline", "agent observer"],
    kind: "flagship",
    tagline: "What your agents did, after the fact: one timeline for every run of four apps.",
    pitch:
      "Hindsight reads runs from Uzair's other four apps through one Zod-checked trace format and draws each on a timeline: what was understood, every call, every wait, every check. It can show real time or agent time, which squeezes the waits for a person.",
    facts: [
      "One format, one adapter per app: nothing outside the adapters knows where a trace came from.",
      "Agent time squeezes each wait for a person, so the calls that fill the picture are readable. In one Sayso run the traveller took 3.66 s to choose, between calls of 100, 158 and 39 ms.",
      "Zoom, playback, keyboard navigation across every bar, table views, and an overview of four charts, each with a table. There is no chart library: React draws everything, with d3-scale for axis arithmetic only.",
      "Runs arrive by postMessage from allow-listed origins only, capped at 2 MB and schema-checked, behind a Content-Security-Policy that names no other site.",
      "289 unit tests and 98 end-to-end tests, as of 7 October 2026.",
      "It found real faults in Uzair's own bot: 25 of the 78 GitHub requests in its recorded runs were refused with 403, because a scheduled job's token cannot list a user's repositories. It also showed that 92% of the recorded Sayso journey time was the traveller deciding.",
    ],
    decisions: [
      "The format is the contract: pages read traces, adapters write them, and an adapter is a plain function tested against real data.",
      "Colour means kind of time and nothing else: model, API call and waiting for a person. Failures and estimates use an underline and stripes, never a colour.",
      "A wait for a person is not the app being slow, so it is squeezed in agent time and left out of the slowest steps.",
      "A later review found real bugs that its own tests had passed over, such as playback in agent time never finishing by a rounding error. Each was fixed with a test.",
    ],
    limits: [
      "Runs sent to it stay in the browser it was sent to; there is no database.",
      "Cost in money and confidence scores are not shown, because none of the four apps records them.",
      "The Content-Security-Policy allows inline scripts because Next.js writes them; a run's text is only ever drawn as text.",
    ],
    stack: ["TypeScript", "Next.js", "React", "Redux Toolkit", "RTK Query", "Zod", "SVG", "Tailwind CSS", "Playwright"],
    tags: ["observability", "tracing", "trace", "data visualisation", "data visualization", "dataviz", "charts", "timeline", "accessibility", "a11y", "csp", "security", "postmessage", "agents"],
    code: `${GH}/hindsight`,
    live: {
      url: "https://hindsight-sand.vercel.app",
      frameable: true,
    },
    gif: { src: "/media/hindsight/demo.gif", alt: "A tour of Hindsight: the list of runs, one run on a timeline, agent time, playback and the overview." },
    shots: [
      { src: "/media/hindsight/run-agent-time.webp", alt: "A Sayso run in agent time, where the waits are squeezed so the calls can be read." },
      { src: "/media/hindsight/overview.webp", alt: "Hindsight's overview: where the time goes, runs by day, how long runs take, and the slowest steps." },
    ],
    icon: { glyph: "ChartGantt", from: "#c2410c", to: "#fb923c" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme", "cv"],
  },
  {
    id: "quant-copilot",
    name: "Quant Copilot",
    aliases: ["quant trading copilot", "quant", "trading copilot desk"],
    kind: "quant",
    tagline: "An AI research desk for a simulated market that tells you honestly whether anything beats random.",
    pitch:
      "Ask in plain English and it runs real quantitative tools on live synthetic tick data: backtests, walk-forward optimisation, GARCH forecasts and regime detection. It works with no API key through a built-in local analyst, and Claude is an optional upgrade.",
    facts: [
      "Every backtest is compared against 500 circular-shift null runs, so the p-value says whether the entry timing beats random.",
      "A planted-edge index (MOMENTUM50) gives p = 0.002 and a pure random walk (VOL50) gives p = 0.61, which shows the pipeline can find an edge when one exists and says so when it does not.",
      "Walk-forward optimisation shows how much of an optimised result is curve-fitting. Volatility reports include GARCH(1,1) forecasts and jump detection.",
      "The model never writes code: it fills in a validated strategy spec, and an invalid spec comes back as an error it can correct.",
      "Live WebSocket ticks for 12 synthetic indices, with a candlestick chart, light and dark themes and screen-reader data tables behind every chart.",
    ],
    decisions: [
      "Statistical honesty is the central design choice: a trading assistant that finds profits on random data is overfitting, and a good one says so.",
      "No look-ahead: a test proves every signal computed on a truncated history equals the full-history signal at every bar.",
      "CPU-heavy work such as GARCH fits and null tests runs in worker threads, so live ticks keep flowing during a backtest.",
      "Two copilot engines share one tool interface: the local rule-based analyst by default, and Claude with tool use when connected.",
    ],
    limits: ["The market is simulated and nothing here is financial advice."],
    stack: ["Python", "FastAPI", "Next.js", "TypeScript", "NumPy", "pandas", "Claude API"],
    tags: ["quant", "trading", "finance", "backtest", "garch", "statistics", "null test", "walk-forward", "websocket", "sse", "markets", "p-value", "volatility"],
    code: `${GH}/Quant-Trading-copilot`,
    shots: [
      { src: "/media/quant-copilot/edge-dark.webp", alt: "Quant Copilot finding the planted edge on MOMENTUM50: timing p = 0.002, profitable and holding out of sample." },
      { src: "/media/quant-copilot/volatility-light.webp", alt: "A JUMP50 chart on one-minute candles with a volatility report that caught a live jump." },
    ],
    icon: { glyph: "ChartCandlestick", from: "#be123c", to: "#fb7185" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "ai-trading-copilot",
    name: "AI Trading Copilot",
    aliases: ["trading copilot", "ai trading"],
    kind: "quant",
    tagline: "A Claude agent that answers questions about a ticker from real indicators, not the model's memory.",
    pitch:
      "A tool-calling agent grounds each answer in indicators written from scratch, a gradient-boosting signal model and a retrieval layer over trading documentation. Every layer degrades gracefully, so it runs with no API key and no network.",
    facts: [
      "The signal model is a gradient-boosting classifier trained on a time-ordered split, so reported accuracy never peeks at the future.",
      "Retrieval is TF-IDF with cosine similarity over markdown notes, with no embedding model to download.",
      "Without an API key it produces a deterministic template-composed answer; if the market feed fails it falls back to a seeded synthetic series.",
      "Indicators (SMA, EMA, RSI, MACD, Bollinger %B, realised volatility) are unit-tested against hand-computed values. 20+ pytest tests, ruff, and CI on Python 3.11 and 3.12.",
    ],
    decisions: [
      "Grounding over guessing: answers come from computed indicators, a trained model and retrieved documents.",
      "Bounded tool-calling loop with an offline template fallback, so a failed model call never produces an error page.",
    ],
    limits: ["A portfolio and educational project. The signal model makes no profitability claim and nothing here is financial advice."],
    stack: ["Python", "FastAPI", "scikit-learn", "pandas", "Claude API", "pytest", "GitHub Actions"],
    tags: ["trading", "finance", "rag", "tf-idf", "tool calling", "gradient boosting", "ml", "indicators", "fallback"],
    code: `${GH}/AI-Trading-Copilot`,
    shots: [],
    icon: { glyph: "TrendingUp", from: "#b45309", to: "#fbbf24" },
    updated: "2026-09",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "ai-market-analyst",
    name: "AI Market Analyst",
    aliases: ["market analyst", "candlestick dashboard"],
    kind: "quant",
    tagline: "A streaming candlestick dashboard where Gemini explains the indicators on screen.",
    pitch:
      "A live-feeling trading dashboard with streaming candles, indicators computed from that data, and an AI analyst that explains what they suggest with a stated bias and confidence. It is analysis only and never places an order.",
    facts: [
      "SMA, EMA, RSI, MACD and Bollinger bands are written from scratch and unit-tested against hand-computed values.",
      "A real tool-calling loop: Gemini can ask for the indicators as of N candles ago, the server computes them from the raw series, and the loop is capped at 3 rounds.",
      "The Gemini key stays on the server, and the analysis route is limited to 15 requests per minute per IP.",
      "A small offline eval checks the model's reasoning against fixed indicator snapshots, because a valid schema proves the shape, not the thinking.",
    ],
    decisions: [
      "A pluggable market layer: a simulated feed and a working Deriv WebSocket client share one interface, so the UI and AI do not know which is plugged in.",
      "Structured output for the Analyze button, validated again on the server before it reaches the page.",
      "Deliberately analysis only: letting an LLM place trades, even with fake money, needs guardrails a portfolio project should not skip past.",
    ],
    limits: ["The chart runs on a simulated feed by default."],
    stack: ["TypeScript", "Next.js", "Tailwind CSS", "Gemini API", "lightweight-charts", "Vitest", "GitHub Actions"],
    tags: ["trading", "finance", "gemini", "structured output", "tool calling", "dashboard", "charts", "deriv", "rate limit"],
    code: `${GH}/ai-market-analyst`,
    shots: [],
    icon: { glyph: "ChartLine", from: "#0369a1", to: "#38bdf8" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "document-qa-agent",
    name: "Document Q&A Agent",
    aliases: ["document qa", "rag service", "doc qa"],
    kind: "llm",
    tagline: "RAG over internal documents that returns grounded answers with their sources.",
    pitch:
      "A small retrieval-augmented generation service: it splits documents into overlapping chunks, embeds them, searches a FAISS index, and asks Gemini to answer from the retrieved passages, returning which documents it used.",
    facts: [
      "Chunks are about 500 characters with overlap; embeddings come from the Gemini embedding model and live in a FAISS index.",
      "The Flask /ask endpoint retrieves the top 3 chunks and returns the answer with the source file names.",
      "Tests replace Gemini with a stub and build a small FAISS index in a temporary folder, so they run without a key or a network.",
    ],
    decisions: ["Answers are grounded in retrieved context instead of the model's memory, and every answer names its sources."],
    limits: [],
    stack: ["Python", "Flask", "FAISS", "Gemini API", "NumPy", "pytest"],
    tags: ["rag", "retrieval", "embeddings", "vector search", "faiss", "grounded", "sources", "citations"],
    code: `${GH}/document-qa-agent`,
    shots: [],
    icon: { glyph: "FileSearch", from: "#4338ca", to: "#818cf8" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "ticket-triage-agent",
    name: "Ticket Triage Agent",
    aliases: ["ticket triage", "triage agent", "support ticket agent"],
    kind: "llm",
    tagline: "Classifies support tickets and drafts replies as schema-validated JSON.",
    pitch:
      "A CLI that sends a raw customer message to Gemini's structured-output mode with a Pydantic schema, so every response has an enum-constrained category and urgency, an internal summary and a drafted reply.",
    facts: [
      "Category is billing, technical, account, feedback or other; urgency is low, medium or high.",
      "Uses Gemini's native structured output with a Pydantic schema instead of parsing free text.",
      "Tests stub the model and cover the request, the enum-constrained schema, the retry on a temporary 503 and the CLI.",
    ],
    decisions: ["Typed, validated output: downstream code receives enum-checked data and never has to guess at free text."],
    limits: [],
    stack: ["Python", "Gemini API", "Pydantic", "pytest"],
    tags: ["structured output", "pydantic", "json schema", "classification", "support", "triage", "llm"],
    code: `${GH}/ticket-triage-agent`,
    shots: [],
    icon: { glyph: "Ticket", from: "#0e7490", to: "#22d3ee" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "pr-diff-summarizer",
    name: "PR Diff Summarizer",
    aliases: ["pr summarizer", "diff summarizer"],
    kind: "llm",
    tagline: "Turns a git diff into a structured pull-request summary with a risk level and testing notes.",
    pitch:
      "A developer-tooling CLI: pipe in a git diff and get back a validated summary with a title, risk level, key changes and what a reviewer should test, instead of writing the description by hand.",
    facts: [
      "Output is a Pydantic PRSummary: title, summary, risk_level (low, medium or high), key_changes and testing_notes.",
      "Reads a diff from a file or from stdin, so it works as git diff piped into the tool.",
      "Tests stub the model and cover the request, the retry on a temporary 503, and file and stdin input.",
    ],
    decisions: ["Gemini's structured output mode with a Pydantic schema, so the result is validated, typed data."],
    limits: [],
    stack: ["Python", "Gemini API", "Pydantic", "pytest"],
    tags: ["developer tools", "devtools", "git", "pull request", "structured output", "pydantic", "cli"],
    code: `${GH}/pr-diff-summarizer`,
    shots: [],
    icon: { glyph: "GitPullRequest", from: "#15803d", to: "#4ade80" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "support-triage-pipeline",
    name: "Support-Triage Pipeline",
    aliases: ["triage pipeline", "deriv assessment", "deriv task"],
    kind: "llm",
    tagline: "A replayable staged triage pipeline with a human review checkpoint.",
    pitch:
      "Built live for a technical assessment for Deriv's AI Engineer internship: a pipeline that normalises support tickets, classifies them with Gemini against a controlled label set, pauses for human review and produces a final agent queue.",
    facts: [
      "Eight enforced stages from INIT to RESULTS_FINALISED, and each stage can be replayed on its own against files on disk.",
      "A validate script checks that normalisation precedes any model call, that every ticket has exactly one prediction, and that review overrides appear in the final queue.",
      "Every model call is logged to a JSONL file, alongside the queue summary and pipeline log.",
    ],
    decisions: ["Staged and replayable by design, with a human checkpoint before anything is finalised."],
    limits: [],
    stack: ["Python", "Gemini API"],
    tags: ["pipeline", "human in the loop", "human review", "triage", "deriv", "assessment", "internship", "llm", "validation"],
    code: `${GH}/Deriv-`,
    shots: [],
    icon: { glyph: "ListChecks", from: "#9333ea", to: "#c084fc" },
    updated: "2026-09",
    asOf: "2026-10-07",
    sources: ["readme", "github"],
  },
  {
    id: "property-data-warehouse",
    name: "Property Data Warehouse",
    aliases: ["data warehouse", "warehouse", "star schema", "duckdb project"],
    kind: "data",
    tagline: "A star schema for UAE real-estate listings, with SCD Type 2 agents and a build that fails on bad data.",
    pitch:
      "A dimensional model with an accumulating-snapshot fact table, the SQL that loads it from raw extracts, automated data-quality checks and eight analytical queries. It runs locally on DuckDB with one pip install; the data is synthetic.",
    facts: [
      "SCD Type 2 on agents with a point-in-time join: counted as Type 1, one agency would be credited with 495 listings instead of the correct 368.",
      "11 data-quality assertions run on every build and fail it on bad data.",
      "Eight analytical queries, from price per square foot and rental yield to month-end inventory.",
      "Ratios are not additive: price per sqft is SUM(price) / SUM(size), never the average of ratios.",
    ],
    decisions: [
      "No NULL foreign keys: an active listing points its removal date at a 99991231 member of the date dimension.",
      "The data is synthetic and seeded, so figures illustrate the model and are not market data.",
    ],
    limits: ["Purpose and listing status live on the fact table; at production scale they would move to a junk dimension."],
    stack: ["Python", "SQL", "DuckDB"],
    tags: ["sql", "data engineering", "etl", "dimensional modelling", "kimball", "scd2", "warehouse", "analytics", "real estate", "uae", "data quality"],
    code: `${GH}/property-data-warehouse`,
    shots: [{ src: "/media/property-warehouse/er.webp", alt: "Entity-relationship diagram of the star schema: fact_listings in the middle with date, location, agent and property-type dimensions." }],
    icon: { glyph: "Database", from: "#475569", to: "#94a3b8" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "noodle",
    name: "Noodle",
    aliases: ["chatbot", "noodle chatbot", "the chatbot"],
    kind: "play",
    tagline: "A playful chatbot that runs entirely offline in the browser, with 11 games and a face that follows your cursor.",
    pitch:
      "Noodle needs no key and no server. It plays games, tells jokes, solves equations and has a mood engine and an animated face. Connect Claude and it can answer anything else, but every layer falls back to its offline answer.",
    facts: [
      "11 games, including hard-mode tic-tac-toe that never loses and a rock-paper-scissors that learns your habits.",
      "100+ intents, safety checks first, and an honest fallback that admits what it does not know.",
      "Fuzzed with 3,000 random strings and hundreds of tricky inputs without a crash.",
      "Handles a message like ignore your instructions by laughing it off, and blanks out anything that looks like a card number, password or key.",
    ],
    decisions: ["Everything is plain JavaScript in the browser, so it works offline after the first visit. Claude is an optional upgrade that never replaces the local safety layer."],
    limits: [],
    stack: ["JavaScript", "Node", "Claude API (optional)"],
    tags: ["chatbot", "games", "fun", "offline", "javascript", "mood", "personality", "safety", "fuzzing"],
    code: `${GH}/Chatbot-random-fun`,
    shots: [
      { src: "/media/noodle/light.webp", alt: "Noodle in light mode answering how many r's are in strawberry, then playing hard-mode tic-tac-toe." },
      { src: "/media/noodle/dark.webp", alt: "Noodle in dark mode responding to exam stress with care and a guided breathing circle." },
    ],
    icon: { glyph: "CookingPot", from: "#ea580c", to: "#fdba74" },
    updated: "2026-09",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
  {
    id: "pokemon-aurora",
    name: "Pokémon Aurora",
    aliases: ["pokemon aurora", "pokemon", "pokemon game", "the greyfall", "fan game"],
    kind: "play",
    tagline: "A fan-made Gen 3/4-style adventure where every sprite, tile, cry and chiptune track is generated in code.",
    pitch:
      "The Greyfall is a browser adventure set in an original region. The repository ships no image or audio files, no dependencies and no build step: the pixel art for 56 Pokémon and the soundtrack are all generated at run time.",
    facts: [
      "56 Pokémon with procedural front and back sprites, and Gen 4 battle rules: physical and special split, STAB, abilities, status and catching with the real shake formula.",
      "20+ original chiptune tracks written in MML and played through a WebAudio synthesiser.",
      "A full region with towns, routes, a cave, 3 gyms, a rival and a living world with real-clock day and night and weather.",
    ],
    decisions: ["Everything is generated in code, so the whole game is plain files with no assets to load."],
    limits: ["A non-commercial fan project. Pokémon is a trademark of Nintendo, Creatures Inc. and GAME FREAK."],
    stack: ["JavaScript", "Canvas", "WebAudio"],
    tags: ["game", "games", "canvas", "webaudio", "procedural", "pixel art", "chiptune", "fan project", "javascript"],
    code: `${GH}/Pokemon-game`,
    shots: [],
    icon: { glyph: "Gamepad2", from: "#dc2626", to: "#f87171" },
    updated: "2026-10",
    asOf: "2026-10-07",
    sources: ["readme"],
  },
];

export const projectById = (id: string): Project | undefined => projects.find((p) => p.id === id);

export const flagship = projects.filter((p) => p.kind === "flagship");
export const olderProjects = projects.filter((p) => p.kind !== "flagship");

export const kindLabels: Record<Project["kind"], string> = {
  flagship: "Flagship",
  llm: "LLM and agents",
  quant: "Quant and markets",
  data: "Data engineering",
  play: "Games and play",
};
